export const Type = {
    ADD_STATE_START: 'ADD_STATE_START',
    ADD_STATE_SUCCESS: 'ADD_STATE_SUCCESS',
    ADD_STATE_ERROR: 'ADD_STATE_ERROR',

    REMOVE_CONTACT_START: 'REMOVE_CONTACT_START',
    REMOVE_CONTACT_SUCCESS: 'REMOVE_CONTACT_SUCCESS',
    REMOVE_CONTACT_ERROR: 'REMOVE_CONTACT_ERROR',

    ADD_CONTACT_START: 'ADD_CONTACT_START',
    ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_ERROR: 'ADD_CONTACT_ERROR',

    // ADD_CONTACT: 'ADD_CONTACT',
    // REMOVE_CONTACT: 'REMOVE_CONTACT',
    FILTER: 'FILTER'
};

